// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rpg
double rpg(int n, double z);
RcppExport SEXP _occPlus_rpg(SEXP nSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(rpg(n, z));
    return rcpp_result_gen;
END_RCPP
}
// samplePGvariables
arma::mat samplePGvariables(arma::mat& Xbeta);
RcppExport SEXP _occPlus_samplePGvariables(SEXP XbetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type Xbeta(XbetaSEXP);
    rcpp_result_gen = Rcpp::wrap(samplePGvariables(Xbeta));
    return rcpp_result_gen;
END_RCPP
}
// diagMatrixProd
arma::mat diagMatrixProd(arma::mat& X, arma::vec& D);
RcppExport SEXP _occPlus_diagMatrixProd(SEXP XSEXP, SEXP DSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type D(DSEXP);
    rcpp_result_gen = Rcpp::wrap(diagMatrixProd(X, D));
    return rcpp_result_gen;
END_RCPP
}
// sample_beta_cpp
arma::vec sample_beta_cpp(arma::mat& X, arma::mat& B, arma::vec& b, arma::vec& Omega, arma::vec& k);
RcppExport SEXP _occPlus_sample_beta_cpp(SEXP XSEXP, SEXP BSEXP, SEXP bSEXP, SEXP OmegaSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type b(bSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type Omega(OmegaSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_beta_cpp(X, B, b, Omega, k));
    return rcpp_result_gen;
END_RCPP
}
// sample_Omega_cpp
arma::vec sample_Omega_cpp(arma::mat& X, arma::vec& beta, arma::vec& n);
RcppExport SEXP _occPlus_sample_Omega_cpp(SEXP XSEXP, SEXP betaSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_Omega_cpp(X, beta, n));
    return rcpp_result_gen;
END_RCPP
}
// sample_beta_nocov_cpp
arma::vec sample_beta_nocov_cpp(arma::vec beta, arma::mat X, arma::vec b, arma::mat B, arma::vec n, arma::vec k);
RcppExport SEXP _occPlus_sample_beta_nocov_cpp(SEXP betaSEXP, SEXP XSEXP, SEXP bSEXP, SEXP BSEXP, SEXP nSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b(bSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_beta_nocov_cpp(beta, X, b, B, n, k));
    return rcpp_result_gen;
END_RCPP
}
// sample_gamma_beta_cpp
List sample_gamma_beta_cpp(arma::vec gamma, arma::vec beta, arma::mat X, arma::vec b, arma::mat B, int D, arma::vec n, arma::vec k, arma::vec indexes_covariates, int fixedIndexes, double d_bar);
RcppExport SEXP _occPlus_sample_gamma_beta_cpp(SEXP gammaSEXP, SEXP betaSEXP, SEXP XSEXP, SEXP bSEXP, SEXP BSEXP, SEXP DSEXP, SEXP nSEXP, SEXP kSEXP, SEXP indexes_covariatesSEXP, SEXP fixedIndexesSEXP, SEXP d_barSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b(bSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type D(DSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type k(kSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type indexes_covariates(indexes_covariatesSEXP);
    Rcpp::traits::input_parameter< int >::type fixedIndexes(fixedIndexesSEXP);
    Rcpp::traits::input_parameter< double >::type d_bar(d_barSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_gamma_beta_cpp(gamma, beta, X, b, B, D, n, k, indexes_covariates, fixedIndexes, d_bar));
    return rcpp_result_gen;
END_RCPP
}
// sample_z_cpp
NumericMatrix sample_z_cpp(const NumericMatrix& w, const NumericMatrix& psi, const NumericMatrix& theta, const NumericVector& theta0, const IntegerVector& M, const IntegerVector& sumM);
RcppExport SEXP _occPlus_sample_z_cpp(SEXP wSEXP, SEXP psiSEXP, SEXP thetaSEXP, SEXP theta0SEXP, SEXP MSEXP, SEXP sumMSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type w(wSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type psi(psiSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type theta0(theta0SEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type sumM(sumMSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_z_cpp(w, psi, theta, theta0, M, sumM));
    return rcpp_result_gen;
END_RCPP
}
// sample_w_cpp
NumericMatrix sample_w_cpp(const NumericMatrix& logy1, double mu0, double sigma0, double mu1, double sigma1, const NumericMatrix& theta, const NumericVector& theta0, const NumericMatrix& p, const NumericMatrix& q, const IntegerVector& M, const IntegerVector& K, const IntegerVector& sumL, const IntegerVector& sumM, const IntegerVector& sumK, int maxL, const NumericMatrix& z);
RcppExport SEXP _occPlus_sample_w_cpp(SEXP logy1SEXP, SEXP mu0SEXP, SEXP sigma0SEXP, SEXP mu1SEXP, SEXP sigma1SEXP, SEXP thetaSEXP, SEXP theta0SEXP, SEXP pSEXP, SEXP qSEXP, SEXP MSEXP, SEXP KSEXP, SEXP sumLSEXP, SEXP sumMSEXP, SEXP sumKSEXP, SEXP maxLSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type logy1(logy1SEXP);
    Rcpp::traits::input_parameter< double >::type mu0(mu0SEXP);
    Rcpp::traits::input_parameter< double >::type sigma0(sigma0SEXP);
    Rcpp::traits::input_parameter< double >::type mu1(mu1SEXP);
    Rcpp::traits::input_parameter< double >::type sigma1(sigma1SEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type theta0(theta0SEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type p(pSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type q(qSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type sumL(sumLSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type sumM(sumMSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type sumK(sumKSEXP);
    Rcpp::traits::input_parameter< int >::type maxL(maxLSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_w_cpp(logy1, mu0, sigma0, mu1, sigma1, theta, theta0, p, q, M, K, sumL, sumM, sumK, maxL, z));
    return rcpp_result_gen;
END_RCPP
}
// sample_pq_cpp
List sample_pq_cpp(NumericMatrix c_imk, NumericMatrix w, IntegerVector primerIdx, IntegerVector idx_k, int maxL, double a_p, double b_p, double a_q, double b_q);
RcppExport SEXP _occPlus_sample_pq_cpp(SEXP c_imkSEXP, SEXP wSEXP, SEXP primerIdxSEXP, SEXP idx_kSEXP, SEXP maxLSEXP, SEXP a_pSEXP, SEXP b_pSEXP, SEXP a_qSEXP, SEXP b_qSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type c_imk(c_imkSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type w(wSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type primerIdx(primerIdxSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type idx_k(idx_kSEXP);
    Rcpp::traits::input_parameter< int >::type maxL(maxLSEXP);
    Rcpp::traits::input_parameter< double >::type a_p(a_pSEXP);
    Rcpp::traits::input_parameter< double >::type b_p(b_pSEXP);
    Rcpp::traits::input_parameter< double >::type a_q(a_qSEXP);
    Rcpp::traits::input_parameter< double >::type b_q(b_qSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_pq_cpp(c_imk, w, primerIdx, idx_k, maxL, a_p, b_p, a_q, b_q));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_occPlus_rpg", (DL_FUNC) &_occPlus_rpg, 2},
    {"_occPlus_samplePGvariables", (DL_FUNC) &_occPlus_samplePGvariables, 1},
    {"_occPlus_diagMatrixProd", (DL_FUNC) &_occPlus_diagMatrixProd, 2},
    {"_occPlus_sample_beta_cpp", (DL_FUNC) &_occPlus_sample_beta_cpp, 5},
    {"_occPlus_sample_Omega_cpp", (DL_FUNC) &_occPlus_sample_Omega_cpp, 3},
    {"_occPlus_sample_beta_nocov_cpp", (DL_FUNC) &_occPlus_sample_beta_nocov_cpp, 6},
    {"_occPlus_sample_gamma_beta_cpp", (DL_FUNC) &_occPlus_sample_gamma_beta_cpp, 11},
    {"_occPlus_sample_z_cpp", (DL_FUNC) &_occPlus_sample_z_cpp, 6},
    {"_occPlus_sample_w_cpp", (DL_FUNC) &_occPlus_sample_w_cpp, 16},
    {"_occPlus_sample_pq_cpp", (DL_FUNC) &_occPlus_sample_pq_cpp, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_occPlus(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
