#' Sample eDNA Metabarcoding Data
#'
#' A list containing an example eDNA metabarcoding dataset used for package vignettes
#' and testing.
#'
#' @format A named list with two elements:
#' \describe{
#'   \item{info}{A \code{data.frame} of metadata with one row per PCR replicate.}
#'   \item{OTU}{A numeric matrix of raw read counts with rows corresponding to replicates and columns to species.}
#' }
#' @source Simulated example data
#' @name data
#' @docType data
"data"

#' Sample Pre-fitted Model Results
#'
#' A pre-fitted \code{occPlus} model object, generated by running \code{runMCMCOccPlus} on
#' the \code{data} example dataset.
#'
#' @format A named list returned by \code{runMCMCOccPlus}, containing posterior arrays and metadata.
#' @source Generated via \code{runMCMCOccPlus(data = data, d = 2, ...)}
#' @name fitmodel
#' @docType data
"fitmodel"

if (getRversion() >= "2.15.1") utils::globalVariables(c(
  ".", "10%", "2.5%", "90%", "97.5%", "E_true", "Factor", "L_true", "M", "N3",
  "Primer", "S", "Sample", "Site", "Species", "Type", "U_output", "U_true",
  "beta_ord_true", "beta_psi_true", "beta_theta_true", "cimk_true",
  "delta", "mu0_true", "mu1_true", "ncov_ord", "p", "p1", "p2", "p_true",
  "primerIdx", "q1", "q2", "q_true", "sd0_true", "sd1_true", "speciesNames",
  "speciesOrder", "sumM", "theta0_true", "theta_true", "w", "y", "z", "z_true"
))
