# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rpg <- function(n, z) {
    .Call('_occPlus_rpg', PACKAGE = 'occPlus', n, z)
}

samplePGvariables <- function(Xbeta) {
    .Call('_occPlus_samplePGvariables', PACKAGE = 'occPlus', Xbeta)
}

diagMatrixProd <- function(X, D) {
    .Call('_occPlus_diagMatrixProd', PACKAGE = 'occPlus', X, D)
}

sample_beta_cpp <- function(X, B, b, Omega, k) {
    .Call('_occPlus_sample_beta_cpp', PACKAGE = 'occPlus', X, B, b, Omega, k)
}

sample_Omega_cpp <- function(X, beta, n) {
    .Call('_occPlus_sample_Omega_cpp', PACKAGE = 'occPlus', X, beta, n)
}

sample_beta_nocov_cpp <- function(beta, X, b, B, n, k) {
    .Call('_occPlus_sample_beta_nocov_cpp', PACKAGE = 'occPlus', beta, X, b, B, n, k)
}

sample_gamma_beta_cpp <- function(gamma, beta, X, b, B, D, n, k, indexes_covariates, fixedIndexes, d_bar) {
    .Call('_occPlus_sample_gamma_beta_cpp', PACKAGE = 'occPlus', gamma, beta, X, b, B, D, n, k, indexes_covariates, fixedIndexes, d_bar)
}

sample_z_cpp <- function(w, psi, theta, theta0, M, sumM) {
    .Call('_occPlus_sample_z_cpp', PACKAGE = 'occPlus', w, psi, theta, theta0, M, sumM)
}

sample_w_cpp <- function(logy1, mu0, sigma0, mu1, sigma1, theta, theta0, p, q, M, K, sumL, sumM, sumK, maxL, z) {
    .Call('_occPlus_sample_w_cpp', PACKAGE = 'occPlus', logy1, mu0, sigma0, mu1, sigma1, theta, theta0, p, q, M, K, sumL, sumM, sumK, maxL, z)
}

sample_pq_cpp <- function(c_imk, w, primerIdx, idx_k, maxL, a_p, b_p, a_q, b_q) {
    .Call('_occPlus_sample_pq_cpp', PACKAGE = 'occPlus', c_imk, w, primerIdx, idx_k, maxL, a_p, b_p, a_q, b_q)
}

